[postgres]
host = "aws-1-us-east-2.pooler.supabase.com"
port = "5432"
database = "postgres"
user = "postgres.txasksvihmiasgyvyhdg"
password = "Cortellini01"

[auth]
# Lista de e-mails que podem entrar no sistema
allowed_emails = [
  "iago.cortellini@gmail.com",
]

[roles]
# Admins identificados por e-mail
admins = [
  "iago.cortellini@gmail.com"
]
