[postgres]
host = "aws-1-us-east-2.pooler.supabase.com"
port = "5432"
database = "postgres"
user = "postgres.txasksvihmiasgyvyhdg"
password = "Cortellini01"

[auth]
clan_password = "12345"

[roles]
admins = ["iago"]
